### ISSUE TITLE
使用教程里的官网链接是不是有点问题

### ISSUE THREAD

**Issue by Super-JX3** [UncleChair/blivechat-dom-onecomme#1]

**Comment by Super-JX3** [comment]
<img width="596" alt="7B129CC156113061C6C87992516CC496" src="https://user-images.githubusercontent.com/103621996/197695357-bab066b5-f936-4b42-9e2a-34862015484d.png">
这里的链接好像指向了错误的网址

**Comment by UncleChair** [comment]
确实，改了
